SELECT DISTINCT CITY 
FROM STATION 
WHERE CITY LIKE BINARY 'I%' 
OR CITY LIKE BINARY 'O%' 
OR CITY LIKE BINARY 'A%' 
OR CITY LIKE BINARY 'U%' 
OR CITY LIKE BINARY 'E%' ;


--Using Regex
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[AEIOU]';
